version: '3.8'
services:
  devs-endava:
    image: openjdk:11
    container_name: devs-endava
    volumes:
      - ./target/billing-0.0.1-SNAPSHOT.jar:/billing-0.0.1-SNAPSHOT.jar
    ports:
      - '80:8080'
    command: ["java","-jar","billing-0.0.1-SNAPSHOT.jar"]